#!/bin/bash

function indentAndSlash {
	cat | sort | \
		sed "s/^.\\//	/" |	\
		sed "s/$/ \\\\/" |		\
		sed "\$s/\\\\//"
}

function indent {
	cat | sort | sed 's/^/	"/' | sed 's/$/"/'
}

function indentAndDir {
	if test "x$1" = "x"; then
		p=""
	else
		p="$1/"
	fi
	cat | sort | sed "s!^!	\"\${CMAKE_CURRENT_LIST_DIR}/$p!" | sed 's/$/"/'
}

# name incDirIfNot"include"
function doDir {
	cd libs/$1
	inc=${2:-include}
	echo "set(mod_$1_INCLUDE_FILES"
	find $inc -iname "*.hpp" | indentAndDir libs/$1
	echo ")"
	echo ""
	echo "set(mod_$1_SRC_FILES"
	find src -iname "*.cpp" | indentAndDir libs/$1
	echo ")"
	echo ""
	if test -d test; then
		echo "set(mod_$1_TEST_CPP_FILES"
		find test -iname "*.cpp" | sed "s/^test\/\(.*\)\.cpp$/\1/" | indent
		echo ")"
		echo ""
		echo "set(mod_$1_TEST_PY_FILES"
		find test -iname "*.py" | sed "s/^test\/\(.*\)\.py$/\1/" | indent
		echo ")"
		echo ""
	fi
	cd ../..
}

function gen_file_lists {
	echo "# Auto-generated by bootstrap.sh"
	doDir gml
	doDir jla_boost
	doDir libmod src
	doDir pymod src
	echo "set(mod_pymod_PY_FILES"
	find libs/pymod/lib -iname "*.py" | indentAndDir
	echo ")"
	echo "set(mod_TEST_PY_FILES"
	find test/py -iname "*.py" | sed -e "s!^test/!!" -e 's!\.py$!!' | indent
	echo ")"
	echo "set(mod_TEST_CPP_FILES"
	find test/cpp -iname "*.cpp" | sed -e "s!^test/!!" -e 's!\.cpp$!!' | indent
	echo ")"
	echo ""
	echo "set(mod_EXAMPLES_PY_FILES"
	find examples/py -iname "*.py" | sed -e "s!^examples/!!" -e 's!\.py$!!' | indent
	echo ")"
}

echo "VERSION"
# public versions are tagged with 'vA.B.0' and private with 'priv-A.B.0'
# these are converted into A.B.0 and A.B.1, with the commit offset as 4th component
v=$(git describe --tags --always --exclude "archive/*" | sed -e "s/^v//" -e 's/priv-\([0-9]*\.[0-9]*\)\.0/\1.1/' -e "s/-g.*$//" -e "s/-/./")
echo $v > VERSION
cat VERSION
echo "CMakeFiles.txt"
gen_file_lists > CMakeFiles.txt
echo "Docs"
doc/makeDocs.sh . || exit 1

echo "Recursing in external/graph_canon"
echo "---------------------------------"
cd external/graph_canon
./bootstrap.sh || exit 1
