include("common.py")

print("Explicit -------------------------------------------------------------")
handleExp(RCExpComposeSub(rcExp(ketoEnol_B), rcExp(aldolAdd_B), True, True))
print("Semi-implicit --------------------------------------------------------")
handleExp(rcExp(ketoEnol_B) * rcSub * rcExp(aldolAdd_B))
print("Implicit -------------------------------------------------------------")
handleExp(ketoEnol_B * rcSub() * aldolAdd_B)
print("Implicit 2 -----------------------------------------------------------")
handleExp(ketoEnol_B * rcSub * aldolAdd_B)
