include("common.py")

print("Explicit -------------------------------------------------------------")
handleExp(RCExpComposeParallel(rcExp(ketoEnol_F), rcExp(aldolAdd_F), True))
print("Semi-implicit --------------------------------------------------------")
handleExp(rcExp(ketoEnol_F) *rcParallel* rcExp(aldolAdd_F))
print("Implicit -------------------------------------------------------------")
handleExp(ketoEnol_F *rcParallel*  aldolAdd_F)
print("Implicit 2 -----------------------------------------------------------")
handleExp(ketoEnol_F *rcParallel(False)* aldolAdd_F)
