include("common.py")

print("Explicit -------------------------------------------------------------")
handleExp(RCExpComposeSuper(rcExp(aldolAdd_B), rcExp(ketoEnol_B), True, True, False))
print("Semi-implicit --------------------------------------------------------")
handleExp(rcExp(aldolAdd_B) * rcSuper * rcExp(ketoEnol_B))
print("Implicit -------------------------------------------------------------")
handleExp(aldolAdd_B * rcSuper() * ketoEnol_B)
print("Implicit 2 -----------------------------------------------------------")
handleExp(aldolAdd_B * rcSuper * ketoEnol_B)
