a = graphGMLString("""graph [
	node [ id 0 label "C" ]
	node [ id 1 label "C" ]
	node [ id 2 label "C" ]
	node [ id 3 label "C" ]
	node [ id 4 label "C" ]
	node [ id 5 label "C" ]
	node [ id 6 label "O" ]
	node [ id 7 label "H" ]
	node [ id 8 label "H" ]
	node [ id 9 label "H" ]
	node [ id 10 label "H" ]
	node [ id 11 label "H" ]
	node [ id 12 label "H" ]
	node [ id 13 label "H" ]
	node [ id 14 label "H" ]
	edge [ source 1 target 0 label "-" ]
	edge [ source 2 target 1 label "-" ]
	edge [ source 3 target 2 label "=" ]
	edge [ source 4 target 3 label "-" ]
	edge [ source 5 target 3 label "-" ]
	edge [ source 5 target 1 label "=" ]
	edge [ source 6 target 5 label "-" ]
	edge [ source 7 target 0 label "-" ]
	edge [ source 8 target 0 label "-" ]
	edge [ source 9 target 0 label "-" ]
	edge [ source 10 target 2 label "-" ]
	edge [ source 11 target 4 label "-" ]
	edge [ source 12 target 4 label "-" ]
	edge [ source 13 target 4 label "-" ]
	edge [ source 14 target 6 label "-" ]
]
""", "a")
b = graphGMLString("""graph [
	node [ id 0 label "H" ]
	node [ id 1 label "H" ]
	node [ id 2 label "H" ]
	node [ id 3 label "H" ]
	node [ id 4 label "C" ]
	node [ id 5 label "H" ]
	node [ id 6 label "H" ]
	node [ id 7 label "O" ]
	node [ id 8 label "H" ]
	node [ id 9 label "C" ]
	node [ id 10 label "H" ]
	node [ id 11 label "C" ]
	node [ id 12 label "C" ]
	node [ id 13 label "C" ]
	node [ id 14 label "C" ]
	edge [ source 13 target 12 label "-" ]
	edge [ source 9 target 13 label "-" ]
	edge [ source 11 target 9 label "=" ]
	edge [ source 4 target 11 label "-" ]
	edge [ source 14 target 11 label "-" ]
	edge [ source 14 target 13 label "=" ]
	edge [ source 7 target 14 label "-" ]
	edge [ source 1 target 12 label "-" ]
	edge [ source 8 target 12 label "-" ]
	edge [ source 5 target 12 label "-" ]
	edge [ source 10 target 9 label "-" ]
	edge [ source 0 target 4 label "-" ]
	edge [ source 3 target 4 label "-" ]
	edge [ source 2 target 4 label "-" ]
	edge [ source 6 target 7 label "-" ]
]
""", "b")
p = ruleGMLString("""rule [
left [
	node [ id 0 label "C" ]
	node [ id 1 label "C" ]
	node [ id 2 label "C" ]
	node [ id 3 label "C" ]
	node [ id 4 label "C" ]
	node [ id 5 label "C" ]
	node [ id 6 label "O" ]
	node [ id 7 label "H" ]
	node [ id 8 label "H" ]
	node [ id 9 label "H" ]
	node [ id 10 label "H" ]
	node [ id 11 label "H" ]
	node [ id 12 label "H" ]
	node [ id 13 label "H" ]
	node [ id 14 label "H" ]
	edge [ source 1 target 0 label "-" ]
	edge [ source 2 target 1 label "-" ]
	edge [ source 3 target 2 label "=" ]
	edge [ source 4 target 3 label "-" ]
	edge [ source 5 target 3 label "-" ]
	edge [ source 5 target 1 label "=" ]
	edge [ source 6 target 5 label "-" ]
	edge [ source 7 target 0 label "-" ]
	edge [ source 8 target 0 label "-" ]
	edge [ source 9 target 0 label "-" ]
	edge [ source 10 target 2 label "-" ]
	edge [ source 11 target 4 label "-" ]
	edge [ source 12 target 4 label "-" ]
	edge [ source 13 target 4 label "-" ]
	edge [ source 14 target 6 label "-" ]
]
right [
	node [ id 90 label "H" ]
	node [ id 91 label "H" ]
	node [ id 92 label "H" ]
	node [ id 93 label "H" ]
	node [ id 94 label "C" ]
	node [ id 95 label "H" ]
	node [ id 96 label "H" ]
	node [ id 97 label "O" ]
	node [ id 98 label "H" ]
	node [ id 99 label "C" ]
	node [ id 910 label "H" ]
	node [ id 911 label "C" ]
	node [ id 912 label "C" ]
	node [ id 913 label "C" ]
	node [ id 914 label "C" ]
	edge [ source 913 target 912 label "-" ]
	edge [ source 99 target 913 label "-" ]
	edge [ source 911 target 99 label "=" ]
	edge [ source 94 target 911 label "-" ]
	edge [ source 914 target 911 label "-" ]
	edge [ source 914 target 913 label "=" ]
	edge [ source 97 target 914 label "-" ]
	edge [ source 91 target 912 label "-" ]
	edge [ source 98 target 912 label "-" ]
	edge [ source 95 target 912 label "-" ]
	edge [ source 910 target 99 label "-" ]
	edge [ source 90 target 94 label "-" ]
	edge [ source 93 target 94 label "-" ]
	edge [ source 92 target 94 label "-" ]
	edge [ source 96 target 97 label "-" ]
]
]""")
dg = dgRuleComp([a], addSubset(a) >> p)
dg.calc()
dg.print()
